import {populationTierFor, type TownProduct} from './types';

/**
 * Launch batch: British Columbia, every town from Tofino to Trail.
 * Populations are approximate (rounded census figures) and est. years are
 * incorporation dates — both get printed on the Certificate of Souvenir, so
 * verify against the town's own records before final Printify art goes out.
 */

type TownSeed = Omit<
  TownProduct,
  'handle' | 'provinceSlug' | 'provinceState' | 'provinceAbbrev' | 'country' | 'populationTier'
>;

const seeds: TownSeed[] = [
  {
    city: 'Tofino',
    population: 2516,
    estYear: 1932,
    knownFor: 'Surfers and fog, in that order',
    style: 'classic-varsity',
    colorway: 'sage',
    newArrival: true,
  },
  {
    city: 'Trail',
    population: 7920,
    estYear: 1901,
    knownFor: 'Home of a very large smelter',
    style: 'faded-slogan',
    colorway: 'ivory',
    slogan: {lead: 'I visited', big: 'THE SMELTER', tail: 'in Trail', marker: 'it was on.'},
    mostOverlooked: true,
    newArrival: true,
  },
  {
    city: 'Abbotsford',
    population: 153524,
    estYear: 1892,
    knownFor: 'Mostly farmland',
    style: 'retro-postcard',
    colorway: 'butter',
    newArrival: true,
  },
  {
    city: 'Chilliwack',
    population: 93203,
    estYear: 1873,
    knownFor: 'Corn, and proud of it',
    style: 'classic-varsity',
    colorway: 'ivory',
  },
  {
    city: 'Kamloops',
    population: 97902,
    estYear: 1893,
    knownFor: 'Two rivers meet here and keep going',
    style: 'classic-varsity',
    colorway: 'brick',
  },
  {
    city: 'Kelowna',
    population: 144576,
    estYear: 1905,
    knownFor: 'A lake monster nobody has seen lately',
    style: 'retro-postcard',
    colorway: 'blue-jean',
  },
  {
    city: 'Vernon',
    population: 44519,
    estYear: 1892,
    knownFor: 'Three lakes within driving distance',
    style: 'classic-varsity',
    colorway: 'butter',
  },
  {
    city: 'Penticton',
    population: 36885,
    estYear: 1908,
    knownFor: 'Between two lakes, on purpose',
    style: 'retro-postcard',
    colorway: 'ivory',
  },
  {
    city: 'Nanaimo',
    population: 99863,
    estYear: 1874,
    knownFor: 'The bar came first',
    style: 'classic-varsity',
    colorway: 'blue-jean',
  },
  {
    city: 'Courtenay',
    population: 28420,
    estYear: 1915,
    knownFor: 'Gateway to somewhere else',
    style: 'faded-slogan',
    colorway: 'sage',
    slogan: {lead: 'I stopped', big: 'FOR GAS', tail: 'in Courtenay', marker: 'then stayed.'},
  },
  {
    city: 'Campbell River',
    population: 35519,
    estYear: 1947,
    knownFor: 'Salmon capital of the world, allegedly',
    style: 'classic-varsity',
    colorway: 'ivory',
  },
  {
    city: 'Port Alberni',
    population: 18259,
    estYear: 1912,
    knownFor: 'A canal that is actually an inlet',
    style: 'retro-postcard',
    colorway: 'brick',
    mostOverlooked: true,
  },
  {
    city: 'Prince George',
    population: 76708,
    estYear: 1915,
    knownFor: 'The capital of northern British Columbia',
    style: 'classic-varsity',
    colorway: 'blue-jean',
  },
  {
    city: 'Prince Rupert',
    population: 12300,
    estYear: 1910,
    knownFor: 'Rainiest city in Canada, most years',
    style: 'faded-slogan',
    colorway: 'blue-jean',
    slogan: {lead: 'I dried off', big: 'EVENTUALLY', tail: 'in Prince Rupert', marker: 'mostly.'},
    newArrival: true,
  },
  {
    city: 'Terrace',
    population: 15920,
    estYear: 1927,
    knownFor: 'Occasional home of the white Kermode bear',
    style: 'classic-varsity',
    colorway: 'sage',
  },
  {
    city: 'Smithers',
    population: 5378,
    estYear: 1921,
    knownFor: 'Alpine theme, enforced by bylaw',
    style: 'retro-postcard',
    colorway: 'ivory',
    newArrival: true,
  },
  {
    city: 'Quesnel',
    population: 9889,
    estYear: 1928,
    knownFor: 'Gold rush adjacent',
    style: 'classic-varsity',
    colorway: 'butter',
    mostOverlooked: true,
  },
  {
    city: 'Williams Lake',
    population: 10947,
    estYear: 1929,
    knownFor: 'The stampede — the other one',
    style: 'classic-varsity',
    colorway: 'brick',
  },
  {
    city: 'Dawson Creek',
    population: 12323,
    estYear: 1936,
    knownFor: 'Mile 0 of the Alaska Highway',
    style: 'retro-postcard',
    colorway: 'butter',
    newArrival: true,
  },
  {
    city: 'Fort St. John',
    population: 21465,
    estYear: 1947,
    knownFor: 'The Energetic City, officially',
    style: 'classic-varsity',
    colorway: 'ivory',
  },
  {
    city: 'Cranbrook',
    population: 20499,
    estYear: 1905,
    knownFor: 'Sunniest city in the province, apparently',
    style: 'classic-varsity',
    colorway: 'butter',
  },
  {
    city: 'Nelson',
    population: 11106,
    estYear: 1897,
    knownFor: 'Heritage buildings and strong opinions',
    style: 'retro-postcard',
    colorway: 'sage',
  },
  {
    city: 'Castlegar',
    population: 8338,
    estYear: 1946,
    knownFor: 'Two rivers, one pulp mill',
    style: 'classic-varsity',
    colorway: 'blue-jean',
    mostOverlooked: true,
  },
  {
    city: 'Revelstoke',
    population: 8275,
    estYear: 1899,
    knownFor: 'Snow, then more snow',
    style: 'faded-slogan',
    colorway: 'ivory',
    slogan: {lead: 'I shoveled', big: 'THE DRIVEWAY', tail: 'in Revelstoke', marker: 'twice.'},
  },
  {
    city: 'Golden',
    population: 3708,
    estYear: 1957,
    knownFor: 'Six national parks nearby, none of them here',
    style: 'classic-varsity',
    colorway: 'butter',
  },
  {
    city: 'Salmon Arm',
    population: 19432,
    estYear: 1905,
    knownFor: 'The arm is a lake',
    style: 'retro-postcard',
    colorway: 'brick',
  },
  {
    city: 'Merritt',
    population: 7051,
    estYear: 1911,
    knownFor: 'Country music capital of Canada, briefly',
    style: 'classic-varsity',
    colorway: 'sage',
    mostOverlooked: true,
  },
  {
    city: 'Hope',
    population: 6686,
    estYear: 1929,
    knownFor: 'Where the highways make up their minds',
    style: 'faded-slogan',
    colorway: 'butter',
    slogan: {lead: 'All my hopes', big: 'ARE IN', tail: 'Hope, B.C.', marker: 'literally.'},
    newArrival: true,
  },
  {
    city: 'Squamish',
    population: 23819,
    estYear: 1948,
    knownFor: 'Between the mountain and the sea, in traffic',
    style: 'classic-varsity',
    colorway: 'blue-jean',
  },
  {
    city: 'Powell River',
    population: 13943,
    estYear: 1955,
    knownFor: 'Two ferries from anywhere',
    style: 'retro-postcard',
    colorway: 'ivory',
    mostOverlooked: true,
  },
  {
    city: 'Duncan',
    population: 5047,
    estYear: 1912,
    knownFor: 'City of Totems',
    style: 'classic-varsity',
    colorway: 'brick',
  },
  {
    city: 'Parksville',
    population: 13642,
    estYear: 1945,
    knownFor: 'Beach sand, measured in kilometres',
    style: 'retro-postcard',
    colorway: 'butter',
  },
  {
    city: 'Ladysmith',
    population: 8990,
    estYear: 1904,
    knownFor: 'Built on a 49th parallel technicality',
    style: 'classic-varsity',
    colorway: 'ivory',
    mostOverlooked: true,
  },
  {
    city: 'Mission',
    population: 41519,
    estYear: 1892,
    knownFor: 'Across the river from everything',
    style: 'classic-varsity',
    colorway: 'sage',
  },
  {
    city: 'White Rock',
    population: 21939,
    estYear: 1957,
    knownFor: 'The rock is real and it is white',
    style: 'retro-postcard',
    colorway: 'blue-jean',
  },
  {
    city: 'Osoyoos',
    population: 5556,
    estYear: 1946,
    knownFor: "Canada's only desert, sort of",
    style: 'faded-slogan',
    colorway: 'brick',
    slogan: {lead: 'I survived', big: 'THE HEAT', tail: 'in Osoyoos', marker: 'barely.'},
    newArrival: true,
  },
  {
    city: '100 Mile House',
    population: 1928,
    estYear: 1965,
    knownFor: 'Exactly one hundred miles from the zero mile post',
    style: 'classic-varsity',
    colorway: 'butter',
    mostOverlooked: true,
  },
  {
    city: 'Kitimat',
    population: 8236,
    estYear: 1953,
    knownFor: 'A town planned entirely in advance',
    style: 'classic-varsity',
    colorway: 'blue-jean',
    mostOverlooked: true,
  },
  {
    city: 'Fernie',
    population: 6320,
    estYear: 1904,
    knownFor: 'The mountain has a ghost rider',
    style: 'retro-postcard',
    colorway: 'sage',
  },
  {
    city: 'Sidney',
    population: 12318,
    estYear: 1952,
    knownFor: 'Booktown by the sea',
    style: 'classic-varsity',
    colorway: 'ivory',
  },
];

function slugify(city: string): string {
  return city
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

export const britishColumbiaTowns: TownProduct[] = seeds.map((seed) => ({
  ...seed,
  handle: `${slugify(seed.city)}-t-shirt`,
  provinceSlug: 'british-columbia',
  provinceState: 'British Columbia',
  provinceAbbrev: 'BC',
  country: 'Canada',
  populationTier: populationTierFor(seed.population),
}));
